---
# tasks file for 2PRecuperatorio

 - name: "Rol: 2PRecuperatorio"
   debug:
     msg: "Inicio de tareas dentro del Rol: 2PRecuperatorio"

 - name: "Crear directorios en /tmp/"
   file:
     path: "/tmp/{{ item }}"
     state: directory
     mode: '0775'
     recurse: yes
   with_items:
     - "alumno"

 
 - name: "Agrego archivo desde template"
   template:
     src: template_01.j2
     dest: /tmp/alumno/datos.txt

